### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Sapiens333** [gmsafir/gmsafir#18]
Hi, 
I am tryng to install the the additional libraries using DOS command. 
- python.exe -m pip install fortranformat
- python.exe -m pip install numpy
I get the following error: 
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)'))': /simple/fortranformat/
...
Could not fetch URL https://pypi.org/simple/fortranformat/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/fortranformat/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)'))) - skipping
ERROR: Could not find a version that satisfies the requirement fortranformat (from versions: none)
ERROR: No matching distribution found for fortranformat

Can you please let me know if there is a potential solution to this error. 

Thank you!

**Comment by gmsafir** [comment]
Hi, it is a python package installation problem. Here is a similar description of problem on a forum (except that the person uses "pip install" instead of "python -m pip install", and the subsequent proposed solutions:
https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi

 Could you please try the proposed solutions ?

**Comment by Sapiens333** [comment]
Thank your for the quick reply. It worked perfectly fine.
