### ISSUE TITLE
Problems with creating a mesh

### ISSUE THREAD

**Issue by nelly-22** [gmsafir/gmsafir#19]
Hello, 

I'm trying to create a simple mesh for an IPE for a 2D analysis, but the mesh is not regular and Safir doesn't run. In the videos on youtube, there isn't shown how to create it, it is only shown how to do the geometry. When I click on "Mesh 2D", Safir does a mesh like this:

![Screenshot 2022-07-05 120106](https://user-images.githubusercontent.com/108728919/177303658-83f27e7a-1dd0-4630-8642-77f43c4bb642.png)

I tried also to transfinite the curves, but it didn't work. Can you help me?

**Comment by nelly-22** [comment]
the error looks like this:

![grafik](https://user-images.githubusercontent.com/108728919/177307650-feed8fe9-d770-4238-a5ed-33d9070cd882.png)

**Comment by gmsafir** [comment]
Could you please upload your .geo and .g4s files? But before uploading, please add a suffix ".txt" to these filenames. Only this .txt format is suported by GIThub

**Comment by nelly-22** [comment]
[Test.g4s.txt](https://github.com/gmsafir/gmsafir/files/9069269/Test.g4s.txt)
[Test.geo.txt](https://github.com/gmsafir/gmsafir/files/9069270/Test.geo.txt)

**Comment by JMFranssen** [comment]
Dear Nelly-22,

it would be nice if you could identify yourself. The SAFIR and GmSAFIR communities are not based on anonymous messages.

The messages with the Determinant < 0 are probably due to the fact that the first line that you used to described the surface was not in the appropriate direction. Invert the 2 points which make this first line in the script and this should solve the problem (or choose another line as the first one line describing the surface).

The mesh can be refined by giving a smaller value of the fourth coordinate of the points in your script. This 4th coordinate is driving the size of the mesh around the point.

Hope this helps.

Jean-Marc

**Comment by nelly-22** [comment]
Yes, thank you.
What do you mean by "identify yourself"? Do I have to show my licence somewhere?
