### ISSUE TITLE
anticlockwise tangents for void

### ISSUE THREAD

**Issue by MPSimu** [gmsafir/gmsafir#23]
Hi, I imported a .iges format file and defined a void. In the void I see the orientation of tangents in clockwise direction. How can I make them anticlockwise to run simulation? Thanks
![image](https://user-images.githubusercontent.com/102736879/182806381-c15bdbe8-26bb-45f4-b3d8-a89c2a4188dd.png)
[V1_D25-20-8Trennwand.igs.txt](https://github.com/gmsafir/gmsafir/files/9258152/V1_D25-20-8Trennwand.igs.txt)
[V1_D25-20-8Trennwand.geo.txt](https://github.com/gmsafir/gmsafir/files/9258153/V1_D25-20-8Trennwand.geo.txt)
?

**Comment by MPSimu** [comment]
I am able to create tangents in anticlockwise direction by deleting and creating new curves but still I get below error in .OUT file:
- VOID # 1
   It is made of   76 frontiers.

 ERROR from subroutine PROPVOID.
   This void has a frontier described clockwise.
   Only Counter clockwise description is allowed.

![image](https://user-images.githubusercontent.com/102736879/183287257-149e19a8-1bf2-4192-a349-24418f15f0d0.png)

**Comment by gmsafir** [comment]
Did you look at the Issue https://github.com/gmsafir/gmsafir/issues/5 ?
Please, upload your .g4s file

**Comment by MPSimu** [comment]
yes. Infact, after reading it I changed the the orientation of tangents to counter clockwise. In attachment there are new files
[V1_D25-20-8Trennwand.geo.txt](https://github.com/gmsafir/gmsafir/files/9280269/V1_D25-20-8Trennwand.geo.txt)
[V1_D25-20-8Trennwand.igs.txt](https://github.com/gmsafir/gmsafir/files/9280270/V1_D25-20-8Trennwand.igs.txt)
[V1_D25-20-8Trennwand.g4s.txt](https://github.com/gmsafir/gmsafir/files/9280273/V1_D25-20-8Trennwand.g4s.txt)
.

**Comment by gmsafir** [comment]
when displaying the normals, you can see on image below that there are 2 problems:
- the zone marked in yellow is not defined as a surface (no label when displaying the elementary tags in surface labels);
- the surfaces 2 and 3 at frontier of the void are not in the anticlockwise orientation
![Capture2](https://user-images.githubusercontent.com/99477211/183380869-10e19194-a0b8-4d1b-97c2-66600e7c45d3.JPG)

**Comment by MPSimu** [comment]
ok I need to make changes again.  Isnt there a direct way of flipping the directions of normals?

**Comment by gmsafir** [comment]
When you start a geometry from scratch in .geo file and you know there are voids, you can care at initial stage of a correct orientation of the neighbouring surfaces and of the void perimeter. Unfortunately, when you import a geometry (igs...) you need to correct by flipping one by one the uncorrect normals

**Comment by MPSimu** [comment]
I modified the geometry. The arrow pointing in direction as yours but getting the error. 
 - VOID # 1
   It is made of   80 frontiers.

 ERROR from subroutine PROPVOID.
   This void has a frontier described clockwise.
   Only Counter clockwise description is allowed.

![image](https://user-images.githubusercontent.com/102736879/183567685-fecce60c-0dd7-4f95-8f54-7dc1630fed92.png)
[V1_D25-20-8Trennwand.g4s.txt](https://github.com/gmsafir/gmsafir/files/9286927/V1_D25-20-8Trennwand.g4s.txt)
[V1_D25-20-8Trennwand.geo.txt](https://github.com/gmsafir/gmsafir/files/9286928/V1_D25-20-8Trennwand.geo.txt)

**Comment by JMFranssen** [comment]
The message that appears in SAFIR talks about VOIDS and then SAFIR stops, because the check on the VOIDS is made in SAFIR before the check on the finite elements.
But, in this case, the problem comes first from the definition of the finite elements in several surfaces (I mean, those which contain material and will be meshed). You can detect the problem:
- either in GmSAFIR when you see that the normal to some surfaces are not pointing in the same direction as others. SAFIR can not run if this is the case because the finite elements will be numbered correctly in some surfaces and not in others. I don't see the axes of coordinates in the picture above but, in GmSAFIR, the normal to the surface must point in the positive direction of Z in a 2D  Thermal problem.
- or in DIAMOND after you ran SAFIR. Plots the mesh (make it as crude as possible) and the node numbers. Put the mouse in one finite element, watch in the spy the 3 nodes that define the element and see if the order is counter clockwise (OK) or clockwise (not OK). All finite elements that belong to the same surface of GmSAFIR will have the same orientation in Diamond, either OK or not OK.

If you don't define the surfaces that contain material properly, there is very little hope that the definition of the VOID can be correct.
Indeed, the void is defined in SAFIR by the borders of the finite elements, either border 1, 2 or 3 in triangular elements. Even if the void is defined in GmSAFIR by lines which are in the appropriate direction, the borders of the finite elements in the mesh will be in the wrong direction if the finite elements are defined in the wrong order.

=> Solve the problem of orientation of the normal in all surfaces before you come back to the definition of the VOIDS.

**Comment by JMFranssen** [comment]
In order to simplify the life of the users, a new version of SAFIR has been created (2022.a.3) in which the frontier that define the VOID can be listed in any order, anticlockwise or clockwise. These frontier don't even have to be adjacent to each other.
This version will be released probably tomorrow (13/09/2022).
