### ISSUE TITLE
Cannot creat IN. file when conducting 3D structural analysis.

### ISSUE THREAD

**Issue by Malcolmfxy** [gmsafir/gmsafir#51]
Hi,
When I try to create the input file in GMSAFIR, the gmsafir will crash and only an incomplete input file can be generated. 
the last few lines of the input file is 
END_FIX
NODOFBEAM
w1631grider.TEM
TRANSLATE 1 1
TRANSLATE 2 4
TRANSLATE 3 4
END_TRANS
w1835grider.TEM

instead of 

END_TIME
IMPRESSION
TIMEPRINT
40.0 20000.0
END_TIMEPR
.
Attached are my geo g4s and tem files.
Thanks very much.
[model details.zip](https://github.com/gmsafir/gmsafir/files/10250871/model.details.zip)

**Comment by Malcolmfxy** [comment]
I found that as long as I set the material properties for the primary beams, the IN. file will not be generated (gmsafir will crush), but if I only set the material properties for the secondary beams, the IN. file can be generated.

**Comment by gmsafir** [comment]
The problem comes from the material translation from thermal to structural : your TEM files contain one material, namely '1835STEEL', that is not defined as structural material (whereas 1631STEEL or inulation are correctly defined).
In the newest uploaded version, this brutal crush of GmSAFIR has been changed into an error in the error bar.

**Comment by Malcolmfxy** [comment]
thanks very much. Now the gmsafir do not crash and it works. I defined a material with name '1835steel' instead of '1835STEEL', and it seems that gmsafir is case-sensitive.
