### ISSUE TITLE
user defined material

### ISSUE THREAD

**Issue by MPSimu** [gmsafir/gmsafir#7]
I want to add user defined material to 2d thermal analysis. The text file content is not acceptable. I attached all the files. Please suggest what modifications are required?
[2dtherm.geo.txt](https://github.com/gmsafir/gmsafir/files/8407023/2dtherm.geo.txt)
[test.IN.txt](https://github.com/gmsafir/gmsafir/files/8407024/test.IN.txt)
[wool.txt](https://github.com/gmsafir/gmsafir/files/8407025/wool.txt)

**Comment by MPSimu** [comment]
Hello, Can I get an reply to my querry?

**Comment by gmsafir** [comment]
Hi,

a user-defined file shall be in the form:
USER[X] [nb], where:
- X is a number of USER material: in your case USER1
- nb is the number of lines : in your case 11

Then, the second line should have 2 more parameters than your first line : in SAFIR2022, there shall be 11 parameters, instead of 9 for SAFIR2019: T,lambda,c,rho,q,Tstart,Tend,hc,hf,emissiv,r, where Tstart where evaporation starts (in degC) and Tend  where evaporation stops (in degC). Typical values are respectively 100degC and 150degC.

Then your next lines are correct.

However, there is another problem linked with "User-defined" in gmsafir, so I will correct it. I let you know rapidly when the bug is fixed

**Comment by MPSimu** [comment]
I think not only additional parameters required but also the order is not matching with old one. 
In version 2019- T, k, c, rho, w, hh, hc, ε, r
In Version 2022- T, k, c, rho, q, Tstart, Tend, hc, hf, ε, r

1) Coefficient of convection for heated and unheated surfaces are in different order
2) Not sure q is the same as in old version water content (w) in kg/m³

**Comment by gmsafir** [comment]
I discussed with Jean-Marc because the terminology chaned a bit on these variables (it was previously confusing). The new names are  : 
- hh: coefficient of convection for heated surface 
- hu: coefficient of convection for unheated surface 
- w: new name of q (kg/m3)
- (the other variables don't have any change)

**Comment by gmsafir** [comment]
Hi, the user-defined material shall now work properly with newest gmsafir.py version
