### ISSUE TITLE
Importing geometry in gmsafir

### ISSUE THREAD

**Issue by Rosario26** [gmsafir/gmsafir#94]
Dears,

I have to model industrial steel buildings and I am trying to import the geometry in gmsafir proceeding as follows:

- creating the unifilar geometry in Autocad;
- exporting in .igs;
- create a new .geo file in Gmsafir;
- merging the .geo file with the .igs geometry.

At the end of this procedure I have a .geo file on which I can work as usual but I noticed that:
- the .geo file doesn't save the geometry once closed and reopened (it's always necessary to merge the .igs file);
- working this way, it seems that the pre-processor gmsafir goes slowly when editing the .geo file with the merged geometry in;
- I am not able to select the geometry entities grouped by colors or autocad original layers (this would help me in assigning beam section types to the 3D structural model).

Attached, it is an example of the geometry I need to import. 
[geometry example.zip](https://github.com/gmsafir/gmsafir/files/14136440/geometry.example.zip)

Is there a more convenient way to do this, avoiding to create the geometry point-by-point in gmsafir?

Many thanks for your attention and kind support.

Rosario

**Comment by gmsafir** [comment]
You do it the correct way:
1/ open a blank .geo file, declare it with "OpenCascade" kernel
2/ do a merge with your .igs file

For a weird reason, Gmsh does not write the merge in the .geo file.
In your .geo file, after the line "SetFactory("OpenCASCADE");", write the following line:
Merge "STRUTTURA EDIFICIO Q_REV02.igs";

It will open correctly everytime you open the project.

For the slow behavior, it is due to the very large number of beams in your structure.
Though I tested a 1D meshing and it is quite fast.

**Comment by Rosario26** [comment]
Solved. Thank you very much.
